### ISSUE TITLE
[QUESTION] Does decoy work with standard library's `unittest`?

### ISSUE THREAD

**Issue by vishaltanwar96** [mcous/decoy#105]
Hi,

Thanks for building this library, I recently encountered an issue with `mypy` and `python-mockito` and started to look for an alternative and stumbled upon decoy. I see that it's compatible with pytest but would it work with unittest as well?

Thanks!

**Comment by mcous** [comment]
I don't use unittest myself, but it should work just fine! The key would be wiring up the before each and after each setup/teardown methods: `self.decoy = Decoy()` for setup and `self.decoy.reset()` for teardown.

I'd love some help getting unittest setup instructions in the docs if you're interested
