### ISSUE TITLE
Use Pandas `DataFrame` objects as rehearsal arguments

### ISSUE THREAD

**Issue by andreaevooq** [mcous/decoy#200]
Hi,

Is this library production ready?

EDIT: is there a way to create stubs where arguments are Pandas DataFrames? It fails with `ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()`. The issue comes from the fact that [here](https://github.com/mcous/decoy/blob/7189c56cf2b6e587e4d706173cf86756dc7c0847/decoy/spy_events.py#L98) `==` is used, which is incompatible with DataFrames since it doesn't return a boolean.

**Comment by mcous** [comment]
> Is this library production ready?

Sure! It's a testing tool, so I would say it's "ready to be used in the test suite of a production library or application."

> is there a way to create stubs where arguments are Pandas DataFrames? It fails with `ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()`. The issue comes from the fact that [here](https://github.com/mcous/decoy/blob/7189c56cf2b6e587e4d706173cf86756dc7c0847/decoy/spy_events.py#L98) == is used, which is incompatible with DataFrames since it doesn't return a boolean.

I'm afraid I don't have any experience with Pandas, so I do not know or understand where that message is coming from or why having a `DataFrame` involved with make an `==` equality expression fail. If you were able to provide a minimal reproduction of the issue you're experiencing, I may be able to assist further

**Comment by mcous** [comment]
> Essentially, in Pandas `__eq__` returns a `DataFrame` that contains the result of applying `==` pairwise on each element. One should use instead [equals](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html) to have a simple boolean as return value (a very unfortunate decision by Pandas' creators IMO).

Yikes, "unfortunate" is right; overriding `==` to return something other than a `bool` is downright hostile to other libraries.

The way Decoy's matchers work is that they define classes with their own `__eq__` methods. I wonder if a similar approach might work here:

```py
class DataFrameMatcher:
    def __init__(self, frame: pd.DataFrame) -> None:
        self._frame = frame

    def __eq__(self, other: object) -> bool:
        return self._frame.equals(other)
```

Usage:

```py
decoy.when(
    some_mock.compute_stuff(
        DataFrameMatcher(dataframe_arg_1),
        DataFrameMatcher(dataframe_arg_2),
        DataFrameMatcher(dataframe_arg_3),
        datetime_1,
        datetime_2,
    )
).then_return(dataframe_return_value)
```

Will take a little bit more work to get that to pass type checking, but baby steps

**Comment by mcous** [comment]
> well done for the library, it's already my favorite for Python

😊 

> Just saw your update, indeed it doesn't work

It doesn't work because there was, in fact, a bug in Decoy's comparison logic! I've resolved that issue in the just-released `v2.0.2`. This now works for me:

```py
import pandas as pd
from decoy import Decoy


class DataFrameMatcher:
    def __init__(self, frame: pd.DataFrame) -> None:
        self._frame = frame

    def __eq__(self, other: object) -> bool:
        return self._frame.equals(other)


data1 = pd.DataFrame({"x1": range(1, 10)})
data2 = pd.DataFrame({"x1": range(1, 10)})
data3 = pd.DataFrame({"x1": range(1, 11)})

decoy = Decoy()

fn = decoy.mock(name="fn")

decoy.when(fn(DataFrameMatcher(data1))).then_return("hello!")

assert fn(data2) == "hello!"
assert fn(data3) is None
print("success!")
```

**Comment by andreaevooq** [comment]
I confirm it works now! Thank you very much!

**Comment by mcous** [comment]
Nice! I don't know if this `==` vs `.equals` thing is common in the world of Python data science libraries, but I would accept a PR that adds a `ByEquals` matcher to compare by an object's `.equals` method, if that's something you think would make your life easier.

The body would look pretty much the same as `DataFrameMatcher` above, but I'd change the type annotations to use `Protocol` duck typing to avoid a dependency on `pandas`

**Comment by andreaevooq** [comment]
I'm aware only of Pandas and NumPy (it uses [array_equal](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html)), but there might be other libraries. 

We're quite satisfied with the current solution, but yes, we might contribute a PR in the future; I just can't guarantee you anything, unfortunately! 

By the way, even before adding new matchers, I think a nice improvement would be to update the docs on how to write custom matchers, I wouldn't have thought of that without your help.
